// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'capabilities_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.StaticReflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.capabilities_test.A',
        134217735,
        0,
        const prefix0.StaticReflector(),
        const <int>[0, 1, 2, 3],
        const <int>[],
        const <int>[0, 1, 2],
        -1,
        {
          r'foo': () => prefix0.A.foo,
          r'boo': () => prefix0.A.boo,
          r'getFoo': () => prefix0.A.getFoo,
        },
        {r'setFoo=': (dynamic value) => prefix0.A.setFoo = value},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        null,
      ),
    ],
    <m.DeclarationMirror>[
      r.MethodMirrorImpl(
        r'foo',
        2097170,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.StaticReflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'boo',
        2097170,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.StaticReflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'getFoo',
        2097171,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.StaticReflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'setFoo=',
        1310740,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[0],
        const prefix0.StaticReflector(),
        null,
      ),
    ],
    <m.ParameterMirror>[
      r.ParameterMirrorImpl(
        r'x',
        134348806,
        3,
        const prefix0.StaticReflector(),
        -1,
        -1,
        -1,
        null,
        null,
        null,
        null,
      ),
    ],
    <Type>[prefix0.A],
    1,
    {},
    {},
    null,
    [],
  ),
  const prefix0.InstanceReflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.B>(
        r'B',
        r'test_reflection.test.capabilities_test.B',
        134217735,
        0,
        const prefix0.InstanceReflector(),
        const <int>[0, 1, 2, 3],
        const <int>[4, 0, 1, 2, 3],
        const <int>[],
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        null,
      ),
    ],
    <m.DeclarationMirror>[
      r.MethodMirrorImpl(
        r'foo',
        2097154,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.InstanceReflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'boo',
        2097154,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.InstanceReflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'getFoo',
        2097155,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.InstanceReflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'setFoo=',
        1310724,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[0],
        const prefix0.InstanceReflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'includedByInvokeInBBase',
        2097154,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.InstanceReflector(),
        null,
      ),
    ],
    <m.ParameterMirror>[
      r.ParameterMirrorImpl(
        r'x',
        134348806,
        3,
        const prefix0.InstanceReflector(),
        -1,
        -1,
        -1,
        null,
        null,
        null,
        null,
      ),
    ],
    <Type>[prefix0.B],
    1,
    {
      r'includedByInvokeInBBase': (dynamic instance) =>
          instance.includedByInvokeInBBase,
      r'foo': (dynamic instance) => instance.foo,
      r'boo': (dynamic instance) => instance.boo,
      r'getFoo': (dynamic instance) => instance.getFoo,
    },
    {r'setFoo=': (dynamic instance, value) => instance.setFoo = value},
    null,
    [],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
