// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'class_property_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.class_property_test.A',
        134218247,
        0,
        const prefix0.Reflector(),
        const <int>[],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {},
        0,
        0,
        const <int>[],
        null,
        null,
      ),
      r.NonGenericClassMirrorImpl(
        r'_B',
        r'test_reflection.test.class_property_test._B',
        134217767,
        1,
        const prefix0.Reflector(),
        const <int>[],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {},
        0,
        1,
        const <int>[],
        null,
        null,
      ),
      r.GenericClassMirrorImpl<prefix0.D>(
        r'D',
        r'test_reflection.test.class_property_test.D',
        134217735,
        2,
        const prefix0.Reflector(),
        const <int>[],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {},
        0,
        2,
        const <int>[],
        null,
        null,
        (o) {
          return o is prefix0.D;
        },
        const <int>[4],
        2,
      ),
      r.NonGenericClassMirrorImpl<prefix0.C>(
        r'C',
        r'test_reflection.test.class_property_test.C',
        138412039,
        3,
        const prefix0.Reflector(),
        const <int>[],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {},
        0,
        3,
        const <int>[],
        null,
        null,
      ),
      r.TypeVariableMirrorImpl(
        r'X',
        r'test_reflection.test.class_property_test.D.X',
        const prefix0.Reflector(),
        -1,
        2,
        null,
      ),
    ],
    <m.DeclarationMirror>[],
    <m.ParameterMirror>[],
    <Type>[
      prefix0.A,
      const r.FakeType(r'test_reflection.test.class_property_test._B'),
      prefix0.D,
      prefix0.C,
    ],
    4,
    {},
    {},
    <m.LibraryMirror>[
      r.LibraryMirrorImpl(
        r'test_reflection.test.class_property_test',
        Uri.parse('package:tom_reflection_test/test/class_property_test.dart'),
        const prefix0.Reflector(),
        const <int>[],
        {},
        {},
        null,
        null,
      ),
    ],
    [],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
