// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'corresponding_setter_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.TopLevelInvokeMetaReflector(): r.ReflectorData(
    <m.TypeMirror>[],
    null,
    null,
    <Type>[],
    0,
    {},
    {},
    <m.LibraryMirror>[
      r.LibraryMirrorImpl(
        r'test_reflection.test.corresponding_setter_test',
        Uri.parse(
          'package:tom_reflection_test/test/corresponding_setter_test.dart',
        ),
        const prefix0.TopLevelInvokeMetaReflector(),
        const <int>[-1],
        {r'fooBar': () => prefix0.fooBar},
        {r'fooBar=': (dynamic value) => prefix0.fooBar = value},
        null,
        {r'fooBar': 0, r'fooBar=': 1},
      ),
    ],
    [
      const [0, 0, null],
      const [1, 0, null],
    ],
  ),
  const prefix0.TopLevelInvokeFrReflector(): r.ReflectorData(
    <m.TypeMirror>[],
    null,
    null,
    <Type>[],
    0,
    {},
    {},
    <m.LibraryMirror>[
      r.LibraryMirrorImpl(
        r'test_reflection.test.corresponding_setter_test',
        Uri.parse(
          'package:tom_reflection_test/test/corresponding_setter_test.dart',
        ),
        const prefix0.TopLevelInvokeFrReflector(),
        const <int>[-1],
        {
          r'invokingMetaReflector': () => prefix0.invokingMetaReflector,
          r'instanceInvokeMetaReflector': () =>
              prefix0.instanceInvokeMetaReflector,
          r'staticInvokeMetaReflector': () => prefix0.staticInvokeMetaReflector,
          r'topLevelInvokeMetaReflector': () =>
              prefix0.topLevelInvokeMetaReflector,
          r'invokingFrReflector': () => prefix0.invokingFrReflector,
          r'instanceInvokeFrReflector': () => prefix0.instanceInvokeFrReflector,
          r'staticInvokeFrReflector': () => prefix0.staticInvokeFrReflector,
          r'topLevelInvokeFrReflector': () => prefix0.topLevelInvokeFrReflector,
          r'fooBar': () => prefix0.fooBar,
        },
        {r'fooBar=': (dynamic value) => prefix0.fooBar = value},
        null,
        {
          r'invokingMetaReflector': 0,
          r'instanceInvokeMetaReflector': 0,
          r'staticInvokeMetaReflector': 0,
          r'topLevelInvokeMetaReflector': 0,
          r'invokingFrReflector': 0,
          r'instanceInvokeFrReflector': 0,
          r'staticInvokeFrReflector': 0,
          r'topLevelInvokeFrReflector': 0,
          r'fooBar': 0,
          r'fooBar=': 1,
        },
      ),
    ],
    [
      const [0, 0, null],
      const [1, 0, null],
    ],
  ),
  const prefix0.InvokingMetaReflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.corresponding_setter_test.A',
        134217735,
        0,
        const prefix0.InvokingMetaReflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        {r'foo': 0, r'foobar': 0, r'foo=': 1, r'foobar=': 1},
      ),
      r.NonGenericClassMirrorImpl<prefix0.B>(
        r'B',
        r'test_reflection.test.corresponding_setter_test.B',
        134217735,
        1,
        const prefix0.InvokingMetaReflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {r'foo': () => prefix0.B.foo, r'foobar': () => prefix0.B.foobar},
        {
          r'foo=': (dynamic value) => prefix0.B.foo = value,
          r'foobar=': (dynamic value) => prefix0.B.foobar = value,
        },
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        {r'foo': 0, r'foobar': 0},
      ),
    ],
    null,
    null,
    <Type>[prefix0.A, prefix0.B],
    2,
    {
      r'foo': (dynamic instance) => instance.foo,
      r'foobar': (dynamic instance) => instance.foobar,
    },
    {
      r'foo=': (dynamic instance, value) => instance.foo = value,
      r'foobar=': (dynamic instance, value) => instance.foobar = value,
    },
    null,
    [
      const [0, 0, null],
      const [1, 0, null],
    ],
  ),
  const prefix0.InstanceInvokeMetaReflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.corresponding_setter_test.A',
        134217735,
        0,
        const prefix0.InstanceInvokeMetaReflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        {r'foo': 0, r'foobar': 0, r'foo=': 1, r'foobar=': 1},
      ),
    ],
    null,
    null,
    <Type>[prefix0.A],
    1,
    {
      r'foo': (dynamic instance) => instance.foo,
      r'foobar': (dynamic instance) => instance.foobar,
    },
    {
      r'foo=': (dynamic instance, value) => instance.foo = value,
      r'foobar=': (dynamic instance, value) => instance.foobar = value,
    },
    null,
    [
      const [0, 0, null],
      const [1, 0, null],
    ],
  ),
  const prefix0.InvokingFrReflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.corresponding_setter_test.A',
        134217735,
        0,
        const prefix0.InvokingFrReflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        {r'foobar': 0, r'foobar=': 1},
      ),
      r.NonGenericClassMirrorImpl<prefix0.B>(
        r'B',
        r'test_reflection.test.corresponding_setter_test.B',
        134217735,
        1,
        const prefix0.InvokingFrReflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {r'foobar': () => prefix0.B.foobar},
        {r'foobar=': (dynamic value) => prefix0.B.foobar = value},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        {r'foobar': 0, r'foobar=': 1},
      ),
    ],
    null,
    null,
    <Type>[prefix0.A, prefix0.B],
    2,
    {r'foobar': (dynamic instance) => instance.foobar},
    {r'foobar=': (dynamic instance, value) => instance.foobar = value},
    null,
    [
      const [0, 0, null],
      const [1, 0, null],
    ],
  ),
  const prefix0.InstanceInvokeFrReflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.corresponding_setter_test.A',
        134217735,
        0,
        const prefix0.InstanceInvokeFrReflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        {r'foobar': 0, r'foobar=': 1},
      ),
    ],
    null,
    null,
    <Type>[prefix0.A],
    1,
    {r'foobar': (dynamic instance) => instance.foobar},
    {r'foobar=': (dynamic instance, value) => instance.foobar = value},
    null,
    [
      const [0, 0, null],
      const [1, 0, null],
    ],
  ),
  const prefix0.StaticInvokeMetaReflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.B>(
        r'B',
        r'test_reflection.test.corresponding_setter_test.B',
        134217735,
        0,
        const prefix0.StaticInvokeMetaReflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {r'foo': () => prefix0.B.foo, r'foobar': () => prefix0.B.foobar},
        {
          r'foo=': (dynamic value) => prefix0.B.foo = value,
          r'foobar=': (dynamic value) => prefix0.B.foobar = value,
        },
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        {r'foo': 0, r'foobar': 0},
      ),
    ],
    null,
    null,
    <Type>[prefix0.B],
    1,
    {},
    {},
    null,
    [
      const [0, 0, null],
      const [1, 0, null],
    ],
  ),
  const prefix0.StaticInvokeFrReflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.B>(
        r'B',
        r'test_reflection.test.corresponding_setter_test.B',
        134217735,
        0,
        const prefix0.StaticInvokeFrReflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {r'foobar': () => prefix0.B.foobar},
        {r'foobar=': (dynamic value) => prefix0.B.foobar = value},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        {r'foobar': 0, r'foobar=': 1},
      ),
    ],
    null,
    null,
    <Type>[prefix0.B],
    1,
    {},
    {},
    null,
    [
      const [0, 0, null],
      const [1, 0, null],
    ],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
