// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tom_reflection_generator.
// https://github.com/al-the-bear/tom_reflection
import 'dart:core';
import 'default_values_lib.dart' as prefix0;
import 'default_values_test.dart' as prefix1;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix1.MyReflection(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix1.A>(
        r'A',
        r'test_reflection.test.default_values_test.A',
        134217735,
        0,
        const prefix1.MyReflection(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {
          r'optional': (bool b) =>
              ([
                x = prefix0.A.localConstant + 31,
                y = identical(prefix1.globalConstant, prefix1.globalConstant),
                z = prefix0.globalConstant + prefix0.globalConstant,
                w = const [
                  String,
                  null,
                  prefix1.myReflection,
                  const prefix1.B(named: 24),
                  const <int, Type>{1: prefix1.A},
                ],
              ]) => b ? prefix1.A.optional(x, y, z, w) : null,
        },
        -1,
        -1,
        const <int>[-1],
        null,
        {},
      ),
    ],
    null,
    null,
    <Type>[prefix1.A],
    1,
    {},
    {},
    null,
    [
      const [4, 4, null],
    ],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
