// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'delegate_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.delegate_test.A',
        134217735,
        0,
        const prefix0.Reflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        {
          r'==': 1,
          r'toString': 0,
          r'noSuchMethod': 1,
          r'hashCode': 0,
          r'runtimeType': 0,
          r'arg0': 0,
          r'arg1': 1,
          r'arg2to4': 2,
          r'argNamed': 3,
          r'+': 1,
          r'[]': 1,
          r'[]=': 3,
          r'indexTarget': 0,
          r'getset': 0,
          r'getsetTarget': 0,
          r'indexTarget=': 1,
          r'getset=': 1,
          r'getsetTarget=': 1,
        },
      ),
    ],
    null,
    null,
    <Type>[prefix0.A],
    1,
    {
      r'==': (dynamic instance) =>
          (x) => instance == x,
      r'toString': (dynamic instance) => instance.toString,
      r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
      r'hashCode': (dynamic instance) => instance.hashCode,
      r'runtimeType': (dynamic instance) => instance.runtimeType,
      r'arg0': (dynamic instance) => instance.arg0,
      r'arg1': (dynamic instance) => instance.arg1,
      r'arg2to4': (dynamic instance) => instance.arg2to4,
      r'argNamed': (dynamic instance) => instance.argNamed,
      r'+': (dynamic instance) =>
          (x) => instance + x,
      r'[]': (dynamic instance) =>
          (x) => instance[x],
      r'[]=': (dynamic instance) =>
          (x, v) => instance[x] = v,
      r'indexTarget': (dynamic instance) => instance.indexTarget,
      r'getset': (dynamic instance) => instance.getset,
      r'getsetTarget': (dynamic instance) => instance.getsetTarget,
    },
    {
      r'indexTarget=': (dynamic instance, value) =>
          instance.indexTarget = value,
      r'getset=': (dynamic instance, value) => instance.getset = value,
      r'getsetTarget=': (dynamic instance, value) =>
          instance.getsetTarget = value,
    },
    null,
    [
      const [0, 0, null],
      const [1, 0, null],
      const [4, 2, null],
      const [
        2,
        0,
        const [#z],
      ],
    ],
  ),
  const prefix0.NameReflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.delegate_test.A',
        134217735,
        0,
        const prefix0.NameReflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        {r'arg0': 0},
      ),
    ],
    null,
    null,
    <Type>[prefix0.A],
    1,
    {r'arg0': (dynamic instance) => instance.arg0},
    {},
    null,
    [
      const [0, 0, null],
    ],
  ),
  const prefix0.MetaReflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.delegate_test.A',
        134217735,
        0,
        const prefix0.MetaReflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        {r'arg1': 0, r'argNamed': 1, r'[]': 0, r'getset': 2},
      ),
    ],
    null,
    null,
    <Type>[prefix0.A],
    1,
    {
      r'arg1': (dynamic instance) => instance.arg1,
      r'argNamed': (dynamic instance) => instance.argNamed,
      r'[]': (dynamic instance) =>
          (x) => instance[x],
      r'getset': (dynamic instance) => instance.getset,
    },
    {},
    null,
    [
      const [1, 0, null],
      const [
        2,
        0,
        const [#z],
      ],
      const [0, 0, null],
    ],
  ),
};

final _memberSymbolMap = {
  const Symbol(r'arg0'): r'arg0',
  const Symbol(r'arg1'): r'arg1',
  const Symbol(r'arg2to4'): r'arg2to4',
  const Symbol(r'argNamed'): r'argNamed',
  const Symbol(r'+'): r'+',
  const Symbol(r'[]'): r'[]',
  const Symbol(r'[]='): r'[]=',
  const Symbol(r'indexTarget'): r'indexTarget',
  const Symbol(r'getset'): r'getset',
  const Symbol(r'getsetTarget'): r'getsetTarget',
  const Symbol(r'indexTarget='): r'indexTarget=',
  const Symbol(r'getset='): r'getset=',
  const Symbol(r'getsetTarget='): r'getsetTarget=',
  const Symbol(r'=='): r'==',
  const Symbol(r'toString'): r'toString',
  const Symbol(r'noSuchMethod'): r'noSuchMethod',
  const Symbol(r'hashCode'): r'hashCode',
  const Symbol(r'runtimeType'): r'runtimeType',
};

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
