// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'generic_instantiation_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.generic_instantiation_test.A',
        134217735,
        0,
        const prefix0.Reflector(),
        const <int>[0],
        const <int>[1, 2, 3, 4, 5],
        const <int>[],
        -1,
        {},
        {},
        {
          r'': (bool b) =>
              () => b ? prefix0.A() : null,
        },
        0,
        0,
        const <int>[],
        const <Object>[
          const prefix0.Component(value: prefix0.someFunction<prefix0.Service>),
        ],
        null,
      ),
    ],
    <m.DeclarationMirror>[
      r.MethodMirrorImpl(
        r'',
        64,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'==',
        2097154,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[0],
        const prefix0.Reflector(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'toString',
        2097154,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'noSuchMethod',
        524290,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[1],
        const prefix0.Reflector(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'hashCode',
        2097155,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'runtimeType',
        2097155,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        const [],
      ),
    ],
    <m.ParameterMirror>[
      r.ParameterMirrorImpl(
        r'other',
        134348806,
        1,
        const prefix0.Reflector(),
        -1,
        -1,
        -1,
        null,
        const [],
        null,
        null,
      ),
      r.ParameterMirrorImpl(
        r'invocation',
        134348806,
        3,
        const prefix0.Reflector(),
        -1,
        -1,
        -1,
        null,
        const [],
        null,
        null,
      ),
    ],
    <Type>[prefix0.A],
    1,
    {
      r'==': (dynamic instance) =>
          (x) => instance == x,
      r'toString': (dynamic instance) => instance.toString,
      r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
      r'hashCode': (dynamic instance) => instance.hashCode,
      r'runtimeType': (dynamic instance) => instance.runtimeType,
    },
    {},
    <m.LibraryMirror>[
      r.LibraryMirrorImpl(
        r'test_reflection.test.generic_instantiation_test',
        Uri.parse(
          'package:tom_reflection_test/test/generic_instantiation_test.dart',
        ),
        const prefix0.Reflector(),
        const <int>[],
        {},
        {},
        const [],
        null,
      ),
    ],
    [],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
