// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'implicit_getter_setter_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.implicit_getter_setter_test.A',
        134217735,
        0,
        const prefix0.Reflector(),
        const <int>[0, 1, 2, 3, 4],
        const <int>[5, 6, 10],
        const <int>[7, 8, 9, 11],
        -1,
        {
          r'f3': () => prefix0.A.f3,
          r'f4': () => prefix0.A.f4,
          r'f5': () => prefix0.A.f5,
        },
        {r'f3=': (dynamic value) => prefix0.A.f3 = value},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        null,
      ),
    ],
    <m.DeclarationMirror>[
      r.VariableMirrorImpl(
        r'f1',
        67239941,
        0,
        const prefix0.Reflector(),
        0,
        -1,
        -1,
        null,
        null,
      ),
      r.VariableMirrorImpl(
        r'f2',
        67240965,
        0,
        const prefix0.Reflector(),
        0,
        -1,
        -1,
        null,
        null,
      ),
      r.VariableMirrorImpl(
        r'f3',
        134348821,
        0,
        const prefix0.Reflector(),
        0,
        -1,
        -1,
        null,
        null,
      ),
      r.VariableMirrorImpl(
        r'f4',
        134349845,
        0,
        const prefix0.Reflector(),
        0,
        -1,
        -1,
        null,
        null,
      ),
      r.VariableMirrorImpl(
        r'f5',
        67142805,
        0,
        const prefix0.Reflector(),
        -1,
        -1,
        -1,
        null,
        null,
      ),
      r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 5),
      r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 1, 6),
      r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 2, 7),
      r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 3, 8),
      r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 4, 9),
      r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 0, 10),
      r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 2, 11),
    ],
    <m.ParameterMirror>[
      r.ParameterMirrorImpl(
        r'value',
        67239942,
        10,
        const prefix0.Reflector(),
        0,
        -1,
        -1,
        null,
        null,
        null,
        null,
      ),
      r.ParameterMirrorImpl(
        r'value',
        134348806,
        11,
        const prefix0.Reflector(),
        0,
        -1,
        -1,
        null,
        null,
        null,
        null,
      ),
    ],
    <Type>[prefix0.A],
    1,
    {
      r'f1': (dynamic instance) => instance.f1,
      r'f2': (dynamic instance) => instance.f2,
    },
    {r'f1=': (dynamic instance, value) => instance.f1 = value},
    null,
    [],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
