// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'inherited_variable_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.C>(
        r'C',
        r'test_reflection.test.inherited_variable_test.C',
        134217735,
        0,
        const prefix0.Reflector(),
        const <int>[],
        const <int>[1, 2, 3, 4, 5, 6, 7],
        const <int>[],
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        null,
      ),
    ],
    <m.DeclarationMirror>[
      r.VariableMirrorImpl(
        r'x',
        134348805,
        -1,
        const prefix0.Reflector(),
        -1,
        -1,
        -1,
        null,
        null,
      ),
      r.MethodMirrorImpl(
        r'==',
        2097154,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[0],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'toString',
        2097154,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'noSuchMethod',
        524290,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[1],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'hashCode',
        2097155,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'runtimeType',
        2097155,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 6),
      r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 0, 7),
    ],
    <m.ParameterMirror>[
      r.ParameterMirrorImpl(
        r'other',
        134348806,
        1,
        const prefix0.Reflector(),
        -1,
        -1,
        -1,
        null,
        null,
        null,
        null,
      ),
      r.ParameterMirrorImpl(
        r'invocation',
        134348806,
        3,
        const prefix0.Reflector(),
        -1,
        -1,
        -1,
        null,
        null,
        null,
        null,
      ),
      r.ParameterMirrorImpl(
        r'value',
        134348806,
        7,
        const prefix0.Reflector(),
        -1,
        -1,
        -1,
        null,
        null,
        null,
        null,
      ),
    ],
    <Type>[prefix0.C],
    1,
    {
      r'==': (dynamic instance) =>
          (x) => instance == x,
      r'toString': (dynamic instance) => instance.toString,
      r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
      r'hashCode': (dynamic instance) => instance.hashCode,
      r'runtimeType': (dynamic instance) => instance.runtimeType,
      r'x': (dynamic instance) => instance.x,
    },
    {r'x=': (dynamic instance, value) => instance.x = value},
    null,
    [],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
