// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'invoker_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.MyReflection(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.invoker_test.A',
        134217735,
        0,
        const prefix0.MyReflection(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {
          r'': (bool b) =>
              (f) => b ? prefix0.A(f) : null,
        },
        -1,
        -1,
        const <int>[-1],
        null,
        {
          r'==': 1,
          r'toString': 0,
          r'noSuchMethod': 1,
          r'hashCode': 0,
          r'runtimeType': 0,
          r'arg0': 0,
          r'arg1': 1,
          r'arg1to3': 2,
          r'argNamed': 3,
          r'f': 0,
          r'f=': 1,
        },
      ),
    ],
    null,
    null,
    <Type>[prefix0.A],
    1,
    {
      r'==': (dynamic instance) =>
          (x) => instance == x,
      r'toString': (dynamic instance) => instance.toString,
      r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
      r'hashCode': (dynamic instance) => instance.hashCode,
      r'runtimeType': (dynamic instance) => instance.runtimeType,
      r'arg0': (dynamic instance) => instance.arg0,
      r'arg1': (dynamic instance) => instance.arg1,
      r'arg1to3': (dynamic instance) => instance.arg1to3,
      r'argNamed': (dynamic instance) => instance.argNamed,
      r'f': (dynamic instance) => instance.f,
    },
    {r'f=': (dynamic instance, value) => instance.f = value},
    null,
    [
      const [0, 0, null],
      const [1, 0, null],
      const [4, 2, null],
      const [
        2,
        0,
        const [#z],
      ],
    ],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
