// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'library_declarations_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.library_declarations_test.A',
        134218247,
        0,
        const prefix0.Reflector(),
        const <int>[],
        const <int>[3, 4, 5, 6, 7],
        const <int>[],
        -1,
        {},
        {},
        {},
        0,
        -1,
        const <int>[-1],
        null,
        null,
      ),
      r.NonGenericClassMirrorImpl<prefix0.B>(
        r'B',
        r'test_reflection.test.library_declarations_test.B',
        134217735,
        1,
        const prefix0.Reflector(),
        const <int>[],
        const <int>[3, 4, 5, 6, 7],
        const <int>[],
        -1,
        {},
        {},
        {},
        0,
        -1,
        const <int>[-1],
        null,
        null,
      ),
    ],
    <m.DeclarationMirror>[
      r.VariableMirrorImpl(
        r'reflector',
        142738581,
        0,
        const prefix0.Reflector(),
        -1,
        2,
        2,
        null,
        null,
      ),
      r.MethodMirrorImpl(
        r'main',
        9699352,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 1),
      r.MethodMirrorImpl(
        r'==',
        2097154,
        -1,
        -1,
        3,
        3,
        null,
        const <int>[0],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'toString',
        2097154,
        -1,
        -1,
        4,
        4,
        null,
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'noSuchMethod',
        524290,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[1],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'hashCode',
        2097155,
        -1,
        -1,
        5,
        5,
        null,
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'runtimeType',
        2097155,
        -1,
        -1,
        6,
        6,
        null,
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
    ],
    <m.ParameterMirror>[
      r.ParameterMirrorImpl(
        r'other',
        134348806,
        2,
        const prefix0.Reflector(),
        -1,
        7,
        7,
        null,
        null,
        null,
        null,
      ),
      r.ParameterMirrorImpl(
        r'invocation',
        134348806,
        4,
        const prefix0.Reflector(),
        -1,
        8,
        8,
        null,
        null,
        null,
        null,
      ),
    ],
    <Type>[
      prefix0.A,
      prefix0.B,
      prefix0.Reflector,
      bool,
      String,
      int,
      Type,
      Object,
      Invocation,
    ],
    2,
    {
      r'==': (dynamic instance) =>
          (x) => instance == x,
      r'toString': (dynamic instance) => instance.toString,
      r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
      r'hashCode': (dynamic instance) => instance.hashCode,
      r'runtimeType': (dynamic instance) => instance.runtimeType,
    },
    {},
    <m.LibraryMirror>[
      r.LibraryMirrorImpl(
        r'test_reflection.test.library_declarations_test',
        Uri.parse(
          'package:tom_reflection_test/test/library_declarations_test.dart',
        ),
        const prefix0.Reflector(),
        const <int>[0, 1],
        {r'reflector': () => prefix0.reflector, r'main': () => prefix0.main},
        {},
        null,
        null,
      ),
    ],
    [],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
