// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'libraries_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[],
    <m.DeclarationMirror>[
      r.MethodMirrorImpl(
        r'myFunction',
        10485784,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
    ],
    <m.ParameterMirror>[],
    <Type>[],
    0,
    {},
    {},
    <m.LibraryMirror>[
      r.LibraryMirrorImpl(
        r'test_reflection.test.libraries_test',
        Uri.parse('package:tom_reflection_test/test/libraries_test.dart'),
        const prefix0.Reflector(),
        const <int>[0],
        {r'myFunction': () => prefix0.myFunction},
        {},
        null,
        null,
      ),
    ],
    [],
  ),
  const prefix0.Reflector2(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.C>(
        r'C',
        r'test_reflection.test.libraries_test.C',
        134217735,
        0,
        const prefix0.Reflector2(),
        const <int>[],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {},
        0,
        -1,
        const <int>[-1],
        const <Object>[prefix0.reflector2],
        null,
      ),
    ],
    <m.DeclarationMirror>[
      r.VariableMirrorImpl(
        r'p',
        142737429,
        0,
        const prefix0.Reflector2(),
        -1,
        1,
        1,
        null,
        const <Object>[const prefix0.Test()],
      ),
      r.VariableMirrorImpl(
        r'q',
        142738581,
        0,
        const prefix0.Reflector2(),
        -1,
        1,
        1,
        null,
        const <Object>[const prefix0.Test()],
      ),
      r.ImplicitGetterMirrorImpl(const prefix0.Reflector2(), 0, 0),
      r.ImplicitGetterMirrorImpl(const prefix0.Reflector2(), 1, 1),
      r.MethodMirrorImpl(
        r'getter',
        10485779,
        0,
        -1,
        2,
        2,
        null,
        const <int>[],
        const prefix0.Reflector2(),
        const <Object>[const prefix0.Test()],
      ),
      r.ImplicitSetterMirrorImpl(const prefix0.Reflector2(), 0, 3),
      r.MethodMirrorImpl(
        r'setter=',
        9699348,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[1],
        const prefix0.Reflector2(),
        const <Object>[const prefix0.Test()],
      ),
    ],
    <m.ParameterMirror>[
      r.ParameterMirrorImpl(
        r'value',
        134348806,
        3,
        const prefix0.Reflector2(),
        -1,
        1,
        1,
        null,
        const [],
        null,
        null,
      ),
      r.ParameterMirrorImpl(
        r'x',
        67141638,
        4,
        const prefix0.Reflector2(),
        -1,
        -1,
        -1,
        null,
        const [],
        null,
        null,
      ),
    ],
    <Type>[prefix0.C, int, String],
    1,
    {},
    {},
    <m.LibraryMirror>[
      r.LibraryMirrorImpl(
        r'test_reflection.test.libraries_test',
        Uri.parse('package:tom_reflection_test/test/libraries_test.dart'),
        const prefix0.Reflector2(),
        const <int>[0, 1, 4, 6],
        {
          r'p': () => prefix0.p,
          r'q': () => prefix0.q,
          r'getter': () => prefix0.getter,
        },
        {
          r'p=': (dynamic value) => prefix0.p = value,
          r'setter=': (dynamic value) => prefix0.setter = value,
        },
        const <Object>[prefix0.reflector],
        null,
      ),
    ],
    [],
  ),
  const prefix0.Reflector3(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.D>(
        r'D',
        r'test_reflection.test.libraries_test.D',
        134217735,
        0,
        const prefix0.Reflector3(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        {},
      ),
    ],
    null,
    null,
    <Type>[prefix0.D],
    1,
    {},
    {},
    null,
    [],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
