// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'literal_type_arguments_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.C>(
        r'C',
        r'test_reflection.test.literal_type_arguments_test.C',
        134217735,
        0,
        const prefix0.Reflector(),
        const <int>[0, 1],
        const <int>[2, 3, 4, 5, 6, 0, 1],
        const <int>[],
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        const <Object>[prefix0.reflector],
        null,
      ),
    ],
    <m.DeclarationMirror>[
      r.MethodMirrorImpl(
        r'foo',
        2097155,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        const <Object>[
          const prefix0.ListMetadata(const <int>[1, 2]),
        ],
      ),
      r.MethodMirrorImpl(
        r'bar',
        2097155,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        const <Object>[
          const prefix0.MapMetadata(const <int, prefix0.Reflector>{
            3: prefix0.reflector,
          }),
        ],
      ),
      r.MethodMirrorImpl(
        r'==',
        2097154,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[0],
        const prefix0.Reflector(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'toString',
        2097154,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'noSuchMethod',
        524290,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[1],
        const prefix0.Reflector(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'hashCode',
        2097155,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'runtimeType',
        2097155,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        const [],
      ),
    ],
    <m.ParameterMirror>[
      r.ParameterMirrorImpl(
        r'other',
        134348806,
        2,
        const prefix0.Reflector(),
        -1,
        -1,
        -1,
        null,
        const [],
        null,
        null,
      ),
      r.ParameterMirrorImpl(
        r'invocation',
        134348806,
        4,
        const prefix0.Reflector(),
        -1,
        -1,
        -1,
        null,
        const [],
        null,
        null,
      ),
    ],
    <Type>[prefix0.C],
    1,
    {
      r'==': (dynamic instance) =>
          (x) => instance == x,
      r'toString': (dynamic instance) => instance.toString,
      r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
      r'hashCode': (dynamic instance) => instance.hashCode,
      r'runtimeType': (dynamic instance) => instance.runtimeType,
      r'foo': (dynamic instance) => instance.foo,
      r'bar': (dynamic instance) => instance.bar,
    },
    {},
    null,
    [],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
