// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'member_capability_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.MyReflection(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.Foo>(
        r'Foo',
        r'test_reflection.test.member_capability_test.Foo',
        134217735,
        0,
        const prefix0.MyReflection(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {
          r'': (bool b) =>
              () => b ? prefix0.Foo() : null,
        },
        -1,
        -1,
        const <int>[-1],
        null,
        {
          r'==': 1,
          r'toString': 0,
          r'noSuchMethod': 1,
          r'hashCode': 0,
          r'runtimeType': 0,
          r'x': 0,
          r'y': 1,
          r'a': 0,
          r'b': 0,
          r'a=': 1,
          r'b=': 1,
        },
      ),
    ],
    null,
    null,
    <Type>[prefix0.Foo],
    1,
    {
      r'==': (dynamic instance) =>
          (x) => instance == x,
      r'toString': (dynamic instance) => instance.toString,
      r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
      r'hashCode': (dynamic instance) => instance.hashCode,
      r'runtimeType': (dynamic instance) => instance.runtimeType,
      r'x': (dynamic instance) => instance.x,
      r'y': (dynamic instance) => instance.y,
      r'a': (dynamic instance) => instance.a,
      r'b': (dynamic instance) => instance.b,
    },
    {
      r'a=': (dynamic instance, value) => instance.a = value,
      r'b=': (dynamic instance, value) => instance.b = value,
    },
    null,
    [
      const [0, 0, null],
      const [1, 0, null],
    ],
  ),
  const prefix0.MyReflection2(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.Foo2>(
        r'Foo2',
        r'test_reflection.test.member_capability_test.Foo2',
        134217735,
        0,
        const prefix0.MyReflection2(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        {r'x': 0, r'b': 0, r'b=': 1},
      ),
    ],
    null,
    null,
    <Type>[prefix0.Foo2],
    1,
    {
      r'x': (dynamic instance) => instance.x,
      r'b': (dynamic instance) => instance.b,
    },
    {r'b=': (dynamic instance, value) => instance.b = value},
    null,
    [
      const [0, 0, null],
      const [1, 0, null],
    ],
  ),
  const prefix0.MyReflection3(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.Foo3>(
        r'Foo3',
        r'test_reflection.test.member_capability_test.Foo3',
        134217735,
        0,
        const prefix0.MyReflection3(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        {r'c': 1, r'c=': 0, r'y': 0, r'b': 1, r'b=': 0},
      ),
    ],
    null,
    null,
    <Type>[prefix0.Foo3],
    1,
    {
      r'c': (dynamic instance) => instance.c,
      r'y': (dynamic instance) => instance.y,
      r'b': (dynamic instance) => instance.b,
    },
    {
      r'c=': (dynamic instance, value) => instance.c = value,
      r'b=': (dynamic instance, value) => instance.b = value,
    },
    null,
    [
      const [1, 0, null],
      const [0, 0, null],
    ],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
