// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'metadata_subtype_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.MyReflection(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.C>(
        r'C',
        r'test_reflection.test.metadata_subtype_test.C',
        134217735,
        0,
        const prefix0.MyReflection(),
        const <int>[0, 1, 2, 3],
        const <int>[0, 1],
        const <int>[2, 3],
        -1,
        {
          r'staticFoo': () => prefix0.C.staticFoo,
          r'staticBar': () => prefix0.C.staticBar,
        },
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        null,
      ),
    ],
    <m.DeclarationMirror>[
      r.MethodMirrorImpl(
        r'foo',
        2097154,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.MyReflection(),
        null,
      ),
      r.MethodMirrorImpl(
        r'bar',
        2097154,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.MyReflection(),
        null,
      ),
      r.MethodMirrorImpl(
        r'staticFoo',
        2097170,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.MyReflection(),
        null,
      ),
      r.MethodMirrorImpl(
        r'staticBar',
        2097170,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.MyReflection(),
        null,
      ),
    ],
    <m.ParameterMirror>[],
    <Type>[prefix0.C],
    1,
    {
      r'foo': (dynamic instance) => instance.foo,
      r'bar': (dynamic instance) => instance.bar,
    },
    {},
    null,
    [],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
