// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'metadata_name_clash_lib.dart' as prefix1;
import 'metadata_name_clash_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.C>(
        r'C',
        r'test_reflection.test.metadata_name_clash_test.C',
        134217735,
        0,
        const prefix0.Reflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        const <Object>[prefix0.reflector, const prefix0.Bar()],
        {},
      ),
    ],
    null,
    null,
    <Type>[prefix0.C],
    1,
    {},
    {},
    null,
    [],
  ),
  const prefix1.Reflector2(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix1.D>(
        r'D',
        r'test_reflection.test.metadata_name_clash_lib.D',
        134217735,
        0,
        const prefix1.Reflector2(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        const <Object>[prefix1.reflector2, const prefix1.Bar()],
        {},
      ),
    ],
    null,
    null,
    <Type>[prefix1.D],
    1,
    {},
    {},
    null,
    [],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
