// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'metadata_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.MyReflection(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.Foo>(
        r'Foo',
        r'test_reflection.test.metadata_test.Foo',
        134217735,
        0,
        const prefix0.MyReflection(),
        const <int>[0, 1],
        const <int>[4, 5, 6, 7, 8, 1, 2, 3],
        const <int>[],
        -1,
        {},
        {},
        {},
        0,
        -1,
        const <int>[-1],
        const <Object>[
          prefix0.myReflection,
          const prefix0.Bar(const {
            prefix0.b: deprecated,
            prefix0.c: const Deprecated('tomorrow'),
            1 + 2: (prefix0.d ? 3 : 4),
            identical(1, 2): 's',
            prefix0.K.p: 6,
          }),
          prefix0.b,
          prefix0.c,
        ],
        null,
      ),
    ],
    <m.DeclarationMirror>[
      r.VariableMirrorImpl(
        r'x',
        134348805,
        0,
        const prefix0.MyReflection(),
        -1,
        -1,
        -1,
        null,
        const <Object>[prefix0.b],
      ),
      r.MethodMirrorImpl(
        r'foo',
        1310722,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.MyReflection(),
        const <Object>[
          const prefix0.Bar(const {}),
          const prefix0.Bar.namedConstructor(const {}),
          prefix0.b,
          prefix0.c,
        ],
      ),
      r.ImplicitGetterMirrorImpl(const prefix0.MyReflection(), 0, 2),
      r.ImplicitSetterMirrorImpl(const prefix0.MyReflection(), 0, 3),
      r.MethodMirrorImpl(
        r'==',
        2097154,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[1],
        const prefix0.MyReflection(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'toString',
        2097154,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.MyReflection(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'noSuchMethod',
        524290,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[2],
        const prefix0.MyReflection(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'hashCode',
        2097155,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.MyReflection(),
        const [],
      ),
      r.MethodMirrorImpl(
        r'runtimeType',
        2097155,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.MyReflection(),
        const [],
      ),
    ],
    <m.ParameterMirror>[
      r.ParameterMirrorImpl(
        r'value',
        134348806,
        3,
        const prefix0.MyReflection(),
        -1,
        -1,
        -1,
        null,
        const [],
        null,
        null,
      ),
      r.ParameterMirrorImpl(
        r'other',
        134348806,
        4,
        const prefix0.MyReflection(),
        -1,
        -1,
        -1,
        null,
        const [],
        null,
        null,
      ),
      r.ParameterMirrorImpl(
        r'invocation',
        134348806,
        6,
        const prefix0.MyReflection(),
        -1,
        -1,
        -1,
        null,
        const [],
        null,
        null,
      ),
    ],
    <Type>[prefix0.Foo],
    1,
    {
      r'==': (dynamic instance) =>
          (x) => instance == x,
      r'toString': (dynamic instance) => instance.toString,
      r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
      r'hashCode': (dynamic instance) => instance.hashCode,
      r'runtimeType': (dynamic instance) => instance.runtimeType,
      r'foo': (dynamic instance) => instance.foo,
      r'x': (dynamic instance) => instance.x,
    },
    {r'x=': (dynamic instance, value) => instance.x = value},
    <m.LibraryMirror>[
      r.LibraryMirrorImpl(
        r'test_reflection.test.metadata_test',
        Uri.parse('package:tom_reflection_test/test/metadata_test.dart'),
        const prefix0.MyReflection(),
        const <int>[],
        {},
        {},
        const <Object>[prefix0.c],
        null,
      ),
    ],
    [],
  ),
  const prefix0.MyReflection2(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.Foo2>(
        r'Foo2',
        r'test_reflection.test.metadata_test.Foo2',
        134217735,
        0,
        const prefix0.MyReflection2(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        {
          r'==': 1,
          r'toString': 0,
          r'noSuchMethod': 1,
          r'hashCode': 0,
          r'runtimeType': 0,
          r'foo': 0,
        },
      ),
    ],
    null,
    null,
    <Type>[prefix0.Foo2],
    1,
    {
      r'==': (dynamic instance) =>
          (x) => instance == x,
      r'toString': (dynamic instance) => instance.toString,
      r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
      r'hashCode': (dynamic instance) => instance.hashCode,
      r'runtimeType': (dynamic instance) => instance.runtimeType,
      r'foo': (dynamic instance) => instance.foo,
    },
    {},
    null,
    [
      const [0, 0, null],
      const [1, 0, null],
    ],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
