// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'mixin_static_const_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.M>(
        r'M',
        r'test_reflection.test.mixin_static_const_test.M',
        134217735,
        0,
        const prefix0.Reflector(),
        const <int>[0, 2],
        const <int>[3, 4, 5, 6, 7],
        const <int>[1],
        -1,
        {r's': () => prefix0.M.s},
        {},
        {
          r'': (bool b) =>
              () => b ? prefix0.M() : null,
        },
        -1,
        -1,
        const <int>[-1],
        null,
        null,
      ),
      r.NonGenericClassMirrorImpl<prefix0.B>(
        r'B',
        r'test_reflection.test.mixin_static_const_test.B',
        134217735,
        1,
        const prefix0.Reflector(),
        const <int>[8],
        const <int>[3, 4, 5, 6, 7],
        const <int>[],
        -1,
        {},
        {},
        {
          r'': (bool b) =>
              () => b ? prefix0.B() : null,
        },
        -1,
        -1,
        const <int>[-1],
        null,
        null,
      ),
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'test_reflection.test.mixin_static_const_test.A with test_reflection.test.mixin_static_const_test.M',
        r'test_reflection.test.mixin_static_const_test.test_reflection.test.mixin_static_const_test.A with test_reflection.test.mixin_static_const_test.M',
        134218311,
        2,
        const prefix0.Reflector(),
        const <int>[],
        const <int>[3, 4, 5, 6, 7],
        const <int>[],
        -1,
        const {},
        const {},
        const {},
        -1,
        -1,
        const <int>[-1],
        null,
        null,
      ),
    ],
    <m.DeclarationMirror>[
      r.VariableMirrorImpl(
        r's',
        134349973,
        0,
        const prefix0.Reflector(),
        -1,
        -1,
        -1,
        null,
        null,
      ),
      r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 1),
      r.MethodMirrorImpl(
        r'',
        64,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'==',
        2097154,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[0],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'toString',
        2097154,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'noSuchMethod',
        524290,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[1],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'hashCode',
        2097155,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'runtimeType',
        2097155,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'',
        64,
        1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
    ],
    <m.ParameterMirror>[
      r.ParameterMirrorImpl(
        r'other',
        134348806,
        3,
        const prefix0.Reflector(),
        -1,
        -1,
        -1,
        null,
        null,
        null,
        null,
      ),
      r.ParameterMirrorImpl(
        r'invocation',
        134348806,
        5,
        const prefix0.Reflector(),
        -1,
        -1,
        -1,
        null,
        null,
        null,
        null,
      ),
    ],
    <Type>[
      prefix0.M,
      prefix0.B,
      const r.FakeType(
        r'test_reflection.test.mixin_static_const_test.test_reflection.test.mixin_static_const_test.A with test_reflection.test.mixin_static_const_test.M',
      ),
    ],
    3,
    {
      r'==': (dynamic instance) =>
          (x) => instance == x,
      r'toString': (dynamic instance) => instance.toString,
      r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
      r'hashCode': (dynamic instance) => instance.hashCode,
      r'runtimeType': (dynamic instance) => instance.runtimeType,
    },
    {},
    null,
    [],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
