// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'new_instance_optional_arguments_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.new_instance_optional_arguments_test.A',
        134217735,
        0,
        const prefix0.Reflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {
          r'a0': (bool b) =>
              ([opt1]) => b ? prefix0.A.a0(opt1) : null,
          r'b0': (bool b) =>
              ([opt1, opt2]) => b ? prefix0.A.b0(opt1, opt2) : null,
          r'c0': (bool b) =>
              ([opt1 = 499]) => b ? prefix0.A.c0(opt1) : null,
          r'd0': (bool b) =>
              ([opt1 = 499, opt2 = 42]) => b ? prefix0.A.d0(opt1, opt2) : null,
          r'a1': (bool b) =>
              (req1, [opt1]) => b ? prefix0.A.a1(req1, opt1) : null,
          r'b1': (bool b) =>
              (req1, [opt1, opt2]) => b ? prefix0.A.b1(req1, opt1, opt2) : null,
          r'c1': (bool b) =>
              (req1, [opt1 = 499]) => b ? prefix0.A.c1(req1, opt1) : null,
          r'd1': (bool b) =>
              (req1, [opt1 = 499, opt2 = 42]) =>
                  b ? prefix0.A.d1(req1, opt1, opt2) : null,
        },
        -1,
        -1,
        const <int>[-1],
        null,
        {},
      ),
      r.NonGenericClassMirrorImpl<prefix0.ClazzA>(
        r'ClazzA',
        r'test_reflection.test.new_instance_optional_arguments_test.ClazzA',
        134217735,
        1,
        const prefix0.Reflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {
          r'': (bool b) =>
              ([property]) => b ? prefix0.ClazzA(property) : null,
        },
        -1,
        -1,
        const <int>[-1],
        null,
        {},
      ),
    ],
    null,
    null,
    <Type>[prefix0.A, prefix0.ClazzA],
    2,
    {},
    {},
    null,
    [
      const [1, 1, null],
      const [2, 2, null],
      const [2, 1, null],
      const [3, 2, null],
    ],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
