// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'new_instance_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.new_instance_test.A',
        134217735,
        0,
        const prefix0.Reflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {
          r'': (bool b) =>
              () => b ? prefix0.A() : null,
          r'positional': (bool b) =>
              (x) => b ? prefix0.A.positional(x) : null,
          r'optional': (bool b) =>
              (x, y, [z = 1, w]) => b ? prefix0.A.optional(x, y, z, w) : null,
          r'argNamed': (bool b) =>
              (x, y, {z = 42, p}) =>
                  b ? prefix0.A.argNamed(x, y, p: p, z: z) : null,
          r'noMeta': (bool bb) =>
              (b) => bb ? prefix0.A.noMeta(b) : null,
          r'aFactory': (bool b) =>
              () => b ? prefix0.A.aFactory() : null,
        },
        -1,
        -1,
        const <int>[-1],
        null,
        {},
      ),
    ],
    null,
    null,
    <Type>[prefix0.A],
    1,
    {},
    {},
    null,
    [
      const [0, 0, null],
      const [1, 0, null],
      const [4, 2, null],
      const [
        2,
        0,
        const [#z, #p],
      ],
    ],
  ),
  const prefix0.MetaReflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.new_instance_test.A',
        134217735,
        0,
        const prefix0.MetaReflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {
          r'': (bool b) =>
              () => b ? prefix0.A() : null,
          r'positional': (bool b) =>
              (x) => b ? prefix0.A.positional(x) : null,
          r'optional': (bool b) =>
              (x, y, [z = 1, w]) => b ? prefix0.A.optional(x, y, z, w) : null,
          r'argNamed': (bool b) =>
              (x, y, {z = 42, p}) =>
                  b ? prefix0.A.argNamed(x, y, p: p, z: z) : null,
          r'aFactory': (bool b) =>
              () => b ? prefix0.A.aFactory() : null,
        },
        -1,
        -1,
        const <int>[-1],
        null,
        {},
      ),
    ],
    null,
    null,
    <Type>[prefix0.A],
    1,
    {},
    {},
    null,
    [
      const [0, 0, null],
      const [1, 0, null],
      const [4, 2, null],
      const [
        2,
        0,
        const [#z, #p],
      ],
    ],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
