// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'new_instance_default_values_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.MyReflection(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.new_instance_default_values_test.A',
        134217735,
        0,
        const prefix0.MyReflection(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {
          r'optional': (bool b) =>
              ([x = prefix0.A.localConstant, y = prefix0.globalConstant]) =>
                  b ? prefix0.A.optional(x, y) : null,
          r'namedOptional': (bool b) =>
              ({x = prefix0.A.localConstant, y = prefix0.globalConstant}) =>
                  b ? prefix0.A.namedOptional(x: x, y: y) : null,
          r'initializingFormal': (bool b) =>
              ([f = prefix0.A.localConstant, g = prefix0.globalConstant]) =>
                  b ? prefix0.A.initializingFormal(f, g) : null,
          r'namedInitializingFormal': (bool b) =>
              ({f = prefix0.A.localConstant, g = prefix0.globalConstant}) =>
                  b ? prefix0.A.namedInitializingFormal(f: f, g: g) : null,
        },
        -1,
        -1,
        const <int>[-1],
        null,
        {},
      ),
    ],
    null,
    null,
    <Type>[prefix0.A],
    1,
    {},
    {},
    null,
    [
      const [2, 2, null],
      const [
        0,
        0,
        const [#x, #y],
      ],
      const [
        0,
        0,
        const [#f, #g],
      ],
    ],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
