// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'no_such_method_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.no_such_method_test.A',
        134217735,
        0,
        const prefix0.Reflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {
          r'': (bool b) =>
              () => b ? prefix0.A() : null,
        },
        0,
        -1,
        const <int>[-1],
        null,
        {
          r'==': 1,
          r'toString': 0,
          r'noSuchMethod': 1,
          r'hashCode': 0,
          r'runtimeType': 0,
          r'arg0': 0,
          r'arg1': 1,
          r'arg2to4': 2,
          r'argNamed': 3,
          r'[]': 1,
          r'[]=': 3,
          r'deepThrow': 1,
          r'deepThrowImpl': 1,
        },
      ),
    ],
    null,
    null,
    <Type>[prefix0.A],
    1,
    {
      r'==': (dynamic instance) =>
          (x) => instance == x,
      r'toString': (dynamic instance) => instance.toString,
      r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
      r'hashCode': (dynamic instance) => instance.hashCode,
      r'runtimeType': (dynamic instance) => instance.runtimeType,
      r'arg0': (dynamic instance) => instance.arg0,
      r'arg1': (dynamic instance) => instance.arg1,
      r'arg2to4': (dynamic instance) => instance.arg2to4,
      r'argNamed': (dynamic instance) => instance.argNamed,
      r'[]': (dynamic instance) =>
          (x) => instance[x],
      r'[]=': (dynamic instance) =>
          (x, v) => instance[x] = v,
      r'deepThrow': (dynamic instance) => instance.deepThrow,
      r'deepThrowImpl': (dynamic instance) => instance.deepThrowImpl,
    },
    {},
    <m.LibraryMirror>[
      r.LibraryMirrorImpl(
        r'test_reflection.test.no_such_method_test',
        Uri.parse('package:tom_reflection_test/test/no_such_method_test.dart'),
        const prefix0.Reflector(),
        const <int>[-1],
        {},
        {},
        null,
        {},
      ),
    ],
    [
      const [0, 0, null],
      const [1, 0, null],
      const [4, 2, null],
      const [
        2,
        0,
        const [#z],
      ],
    ],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
