// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'no_type_relations_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.Foo>(
        r'Foo',
        r'.Foo',
        134217735,
        0,
        const prefix0.Reflector(),
        const <int>[],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        null,
      ),
      r.NonGenericClassMirrorImpl<prefix0.Bar>(
        r'Bar',
        r'.Bar',
        134217735,
        1,
        const prefix0.Reflector(),
        const <int>[],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        null,
      ),
      r.NonGenericClassMirrorImpl<Object>(
        r'Object',
        r'dart.core.Object',
        134217735,
        2,
        const prefix0.Reflector(),
        const <int>[],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        null,
      ),
    ],
    <m.DeclarationMirror>[],
    <m.ParameterMirror>[],
    <Type>[prefix0.Foo, prefix0.Bar, Object],
    3,
    {},
    {},
    null,
    [],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
