// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'prefixed_reflector_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.D>(
        r'D',
        r'test_reflection.test.prefixed_reflector_test.D',
        134217735,
        0,
        const prefix0.Reflector(),
        const <int>[1, 2],
        const <int>[3, 4, 5, 6, 7, 1, 2],
        const <int>[],
        -1,
        {},
        {},
        {},
        0,
        -1,
        const <int>[-1],
        null,
        null,
      ),
    ],
    <m.DeclarationMirror>[
      r.MethodMirrorImpl(
        r'main',
        9699352,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'getter',
        2097155,
        0,
        -1,
        1,
        1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'setter=',
        1310724,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[0],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'==',
        2097154,
        -1,
        -1,
        2,
        2,
        null,
        const <int>[1],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'toString',
        2097154,
        -1,
        -1,
        3,
        3,
        null,
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'noSuchMethod',
        524290,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[2],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'hashCode',
        2097155,
        -1,
        -1,
        1,
        1,
        null,
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
      r.MethodMirrorImpl(
        r'runtimeType',
        2097155,
        -1,
        -1,
        4,
        4,
        null,
        const <int>[],
        const prefix0.Reflector(),
        null,
      ),
    ],
    <m.ParameterMirror>[
      r.ParameterMirrorImpl(
        r'owtytrof',
        134348806,
        2,
        const prefix0.Reflector(),
        -1,
        1,
        1,
        null,
        null,
        null,
        null,
      ),
      r.ParameterMirrorImpl(
        r'other',
        134348806,
        3,
        const prefix0.Reflector(),
        -1,
        5,
        5,
        null,
        null,
        null,
        null,
      ),
      r.ParameterMirrorImpl(
        r'invocation',
        134348806,
        5,
        const prefix0.Reflector(),
        -1,
        6,
        6,
        null,
        null,
        null,
        null,
      ),
    ],
    <Type>[prefix0.D, int, bool, String, Type, Object, Invocation],
    1,
    {
      r'==': (dynamic instance) =>
          (x) => instance == x,
      r'toString': (dynamic instance) => instance.toString,
      r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
      r'hashCode': (dynamic instance) => instance.hashCode,
      r'runtimeType': (dynamic instance) => instance.runtimeType,
      r'getter': (dynamic instance) => instance.getter,
    },
    {r'setter=': (dynamic instance, value) => instance.setter = value},
    <m.LibraryMirror>[
      r.LibraryMirrorImpl(
        r'test_reflection.test.prefixed_reflector_test',
        Uri.parse(
          'package:tom_reflection_test/test/prefixed_reflector_test.dart',
        ),
        const prefix0.Reflector(),
        const <int>[0],
        {r'main': () => prefix0.main},
        {},
        null,
        null,
      ),
    ],
    [],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
