// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'proxy_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.ProxyReflection(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.proxy_test.A',
        134217735,
        0,
        const prefix0.ProxyReflection(),
        const <int>[0, 1, 2],
        const <int>[5, 6, 7, 8, 9, 1, 2, 3, 4],
        const <int>[],
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        null,
      ),
    ],
    <m.DeclarationMirror>[
      r.VariableMirrorImpl(
        r'i',
        134348805,
        0,
        const prefix0.ProxyReflection(),
        -1,
        -1,
        -1,
        null,
        null,
      ),
      r.MethodMirrorImpl(
        r'foo',
        2097154,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.ProxyReflection(),
        null,
      ),
      r.MethodMirrorImpl(
        r'bar',
        1310722,
        0,
        -1,
        -1,
        -1,
        null,
        const <int>[0],
        const prefix0.ProxyReflection(),
        null,
      ),
      r.ImplicitGetterMirrorImpl(const prefix0.ProxyReflection(), 0, 3),
      r.ImplicitSetterMirrorImpl(const prefix0.ProxyReflection(), 0, 4),
      r.MethodMirrorImpl(
        r'==',
        2097154,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[2],
        const prefix0.ProxyReflection(),
        null,
      ),
      r.MethodMirrorImpl(
        r'toString',
        2097154,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.ProxyReflection(),
        null,
      ),
      r.MethodMirrorImpl(
        r'noSuchMethod',
        524290,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[3],
        const prefix0.ProxyReflection(),
        null,
      ),
      r.MethodMirrorImpl(
        r'hashCode',
        2097155,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.ProxyReflection(),
        null,
      ),
      r.MethodMirrorImpl(
        r'runtimeType',
        2097155,
        -1,
        -1,
        -1,
        -1,
        null,
        const <int>[],
        const prefix0.ProxyReflection(),
        null,
      ),
    ],
    <m.ParameterMirror>[
      r.ParameterMirrorImpl(
        r'i',
        134348806,
        2,
        const prefix0.ProxyReflection(),
        -1,
        -1,
        -1,
        null,
        null,
        null,
        null,
      ),
      r.ParameterMirrorImpl(
        r'value',
        134348806,
        4,
        const prefix0.ProxyReflection(),
        -1,
        -1,
        -1,
        null,
        null,
        null,
        null,
      ),
      r.ParameterMirrorImpl(
        r'other',
        134348806,
        5,
        const prefix0.ProxyReflection(),
        -1,
        -1,
        -1,
        null,
        null,
        null,
        null,
      ),
      r.ParameterMirrorImpl(
        r'invocation',
        134348806,
        7,
        const prefix0.ProxyReflection(),
        -1,
        -1,
        -1,
        null,
        null,
        null,
        null,
      ),
    ],
    <Type>[prefix0.A],
    1,
    {
      r'==': (dynamic instance) =>
          (x) => instance == x,
      r'toString': (dynamic instance) => instance.toString,
      r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
      r'hashCode': (dynamic instance) => instance.hashCode,
      r'runtimeType': (dynamic instance) => instance.runtimeType,
      r'foo': (dynamic instance) => instance.foo,
      r'bar': (dynamic instance) => instance.bar,
      r'i': (dynamic instance) => instance.i,
    },
    {r'i=': (dynamic instance, value) => instance.i = value},
    null,
    [],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
