// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'reflect_type_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.reflect_type_test.A',
        134217735,
        0,
        const prefix0.Reflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {},
        -1,
        -1,
        const <int>[-1],
        null,
        {},
      ),
    ],
    null,
    null,
    <Type>[prefix0.A],
    1,
    {},
    {},
    null,
    [],
  ),
  const prefix0.BroadReflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.reflect_type_test.A',
        134217735,
        0,
        const prefix0.BroadReflector(),
        const <int>[],
        const <int>[],
        const <int>[],
        -1,
        {},
        {},
        {},
        0,
        0,
        const <int>[],
        const <Object>[prefix0.reflector, prefix0.broadReflector],
        null,
      ),
    ],
    <m.DeclarationMirror>[],
    <m.ParameterMirror>[],
    <Type>[prefix0.A],
    1,
    {},
    {},
    <m.LibraryMirror>[
      r.LibraryMirrorImpl(
        r'test_reflection.test.reflect_type_test',
        Uri.parse('package:tom_reflection_test/test/reflect_type_test.dart'),
        const prefix0.BroadReflector(),
        const <int>[],
        {},
        {},
        const [],
        null,
      ),
    ],
    [],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
