// This file has been generated by the reflection package.
// https://github.com/dart-lang/reflection.
import 'dart:core';
import 'subtype_quantify_test.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import
// ignore_for_file: sdk_version_since

import 'package:tom_reflection/src/reflection/mirrors.dart' as m;
import 'package:tom_reflection/generated.dart' as r;
import 'package:tom_reflection/tom_reflection.dart' as r show Reflection;

final _data = <r.Reflection, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
    <m.TypeMirror>[
      r.NonGenericClassMirrorImpl<prefix0.A>(
        r'A',
        r'test_reflection.test.subtype_quantify_test.A',
        134217735,
        0,
        const prefix0.Reflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {},
        -1,
        0,
        const <int>[],
        null,
        {
          r'==': 1,
          r'toString': 0,
          r'noSuchMethod': 1,
          r'hashCode': 0,
          r'runtimeType': 0,
          r'foo': 0,
        },
      ),
      r.NonGenericClassMirrorImpl<prefix0.B>(
        r'B',
        r'test_reflection.test.subtype_quantify_test.B',
        134217735,
        1,
        const prefix0.Reflector(),
        const <int>[-1],
        null,
        null,
        0,
        {},
        {},
        {},
        -1,
        1,
        const <int>[],
        null,
        {
          r'==': 1,
          r'toString': 0,
          r'noSuchMethod': 1,
          r'hashCode': 0,
          r'runtimeType': 0,
          r'foo': 0,
        },
      ),
      r.NonGenericClassMirrorImpl<prefix0.C>(
        r'C',
        r'test_reflection.test.subtype_quantify_test.C',
        134217735,
        2,
        const prefix0.Reflector(),
        const <int>[-1],
        null,
        null,
        -1,
        {},
        {},
        {},
        -1,
        2,
        const <int>[0],
        null,
        {
          r'==': 1,
          r'toString': 0,
          r'noSuchMethod': 1,
          r'hashCode': 0,
          r'runtimeType': 0,
          r'foo': 0,
        },
      ),
      r.NonGenericClassMirrorImpl<prefix0.C>(
        r'test_reflection.test.subtype_quantify_test.C with test_reflection.test.subtype_quantify_test.M',
        r'test_reflection.test.subtype_quantify_test.test_reflection.test.subtype_quantify_test.C with test_reflection.test.subtype_quantify_test.M',
        134218311,
        3,
        const prefix0.Reflector(),
        const <int>[-1],
        null,
        null,
        2,
        const {},
        const {},
        const {},
        -1,
        -1,
        const <int>[],
        null,
        {
          r'==': 1,
          r'toString': 0,
          r'noSuchMethod': 1,
          r'hashCode': 0,
          r'runtimeType': 0,
          r'foo': 0,
        },
      ),
      r.NonGenericClassMirrorImpl<prefix0.C>(
        r'test_reflection.test.subtype_quantify_test.C with test_reflection.test.subtype_quantify_test.M',
        r'test_reflection.test.subtype_quantify_test.test_reflection.test.subtype_quantify_test.C with test_reflection.test.subtype_quantify_test.M',
        134218311,
        4,
        const prefix0.Reflector(),
        const <int>[-1],
        null,
        null,
        2,
        const {},
        const {},
        const {},
        -1,
        -1,
        const <int>[],
        null,
        {
          r'==': 1,
          r'toString': 0,
          r'noSuchMethod': 1,
          r'hashCode': 0,
          r'runtimeType': 0,
          r'foo': 0,
        },
      ),
      r.NonGenericClassMirrorImpl<prefix0.D>(
        r'D',
        r'test_reflection.test.subtype_quantify_test.D',
        134217735,
        5,
        const prefix0.Reflector(),
        const <int>[-1],
        null,
        null,
        3,
        {},
        {},
        {},
        -1,
        5,
        const <int>[],
        null,
        {
          r'==': 1,
          r'toString': 0,
          r'noSuchMethod': 1,
          r'hashCode': 0,
          r'runtimeType': 0,
          r'foo': 0,
        },
      ),
      r.NonGenericClassMirrorImpl<prefix0.E>(
        r'E',
        r'test_reflection.test.subtype_quantify_test.E',
        134217735,
        6,
        const prefix0.Reflector(),
        const <int>[-1],
        null,
        null,
        4,
        {},
        {},
        {},
        -1,
        6,
        const <int>[],
        null,
        {
          r'==': 1,
          r'toString': 0,
          r'noSuchMethod': 1,
          r'hashCode': 0,
          r'runtimeType': 0,
          r'foo': 0,
        },
      ),
    ],
    null,
    null,
    <Type>[
      prefix0.A,
      prefix0.B,
      prefix0.C,
      const r.FakeType(
        r'test_reflection.test.subtype_quantify_test.test_reflection.test.subtype_quantify_test.C with test_reflection.test.subtype_quantify_test.M',
      ),
      const r.FakeType(
        r'test_reflection.test.subtype_quantify_test.test_reflection.test.subtype_quantify_test.C with test_reflection.test.subtype_quantify_test.M',
      ),
      prefix0.D,
      prefix0.E,
    ],
    7,
    {
      r'==': (dynamic instance) =>
          (x) => instance == x,
      r'toString': (dynamic instance) => instance.toString,
      r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
      r'hashCode': (dynamic instance) => instance.hashCode,
      r'runtimeType': (dynamic instance) => instance.runtimeType,
      r'foo': (dynamic instance) => instance.foo,
    },
    {},
    null,
    [
      const [0, 0, null],
      const [1, 0, null],
    ],
  ),
};

final _memberSymbolMap = null;

void initializeReflection() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
